### ISSUE TITLE
cannot import name ABC

### ISSUE THREAD

**Issue by pribadihcr** [karoldvl/echonet#1]
Hi @karoldvl ,

I tried to run the example code of esc_convnet_paper.py.
I got the following error:
ImportError: cannot import name ABC

Thanks

**Comment by karolpiczak** [comment]
I'm sorry, this project is still a work in progress, in a very rough state. For the time being, Python 3.5 is required. I will most probably backport it to earlier versions/Python 2.7 when the codebase stabilizes a little bit.

**Comment by ankitshah009** [comment]
Dependencies of code to run in python3
sudo apt-get install python3 spython3-dev python3-pip python3-setuptools python3-tk
sudo python3 -m pip install librosa pandas tqdm pydub

**Comment by mynameisvinn** [comment]
should be:

```
sudo apt-get install python3 python3-dev python3-pip python3-setuptools python3-tk
```
