### ISSUE TITLE
Error Running esc_convnet_paper.py

### ISSUE THREAD

**Issue by yujulucy** [karoldvl/echonet#4]
Hi, I am trying to run esc_convnet_paper.py, but came across the error:
ImportError: No module named 'keras'

However, I have followed the instructions as to install the required dependencies: 
sudo pip install -r requirements.txt
After running the command, the following is shown: Successfully installed keras-2.0.8 pyyaml-3.12

May I know what could have caused this problem? Thank you.

**Comment by karolpiczak** [comment]
Are you sure you're using the same Python installation/virtual env as `pip`? Maybe `pip3`?

Maybe this will guide you:
https://stackoverflow.com/questions/39930952/cannot-import-keras-after-installation

**Comment by yujulucy** [comment]
I tried both pip and pip3. Will there be a problem if I am working on VMWorkstation? I will check that link out, thanks!

**Comment by karolpiczak** [comment]
I'm not sure what could be causing this. Is `pip freeze` listing Keras as installed?

**Comment by yujulucy** [comment]
Yes, pip freeze list Keras==2.0.8

**Comment by karolpiczak** [comment]
That's weird. Maybe trying from scratch with a new virtualenv could help.
